### ISSUE TITLE
Spam in console

### ISSUE THREAD

**Issue by AlmostPanda** [char3210/SlimefunAdvancements#16]
When I click on any category it sends this kind of spam in console, it also happens when I click anywhere in any gui like sf guide.

![image](https://github.com/char3210/SlimefunAdvancements/assets/141587317/cb56008b-753e-4ab3-add0-5d73237bf57c)

**Comment by char3210** [comment]
i moved the build to blob builds (https://blob.build/project/SlimefunAdvancements), you will have to update manually but it should have the patch

**Comment by AlmostPanda** [comment]
looks like it works, btw do you know any news about the crafting type criterion?

**Comment by char3210** [comment]
build 3 on blob builds should have it, see readme
