### ISSUE TITLE
Add crafting criteria

### ISSUE THREAD

**Issue by samidont0817** [char3210/SlimefunAdvancements#3]
Would it be possible to also add a block-breaking and mob-killing criteria by chance? We want to use SFAdvancements as a quest system. Adding these criteria would give the ability for more quests to be made. 
Also excited for the slimefun craft criteria to come out.

**Comment by qwertyuioplkjhgfd** [comment]
might add mob killing

block breaking might be difficult though, since unless you only want to make quests with breaking only one block, i would need to prevent people from repeatedly breaking and replacing the block. i could do a system where placing a block would reduce your progress, but there's ways around it, such as through block placers or having a friend place the blocks for you, etc.

**Comment by samidont0817** [comment]
Awesome! If you could make block breaking work that would be cool, but I understand what you are saying. Excited for the plugin!

**Comment by qwertyuioplkjhgfd** [comment]
mob killing added

**Comment by samidont0817** [comment]
Awesome. Thank you so much!

**Comment by samidont0817** [comment]
Also, Question. Can you do like an X amount of mobs for the mobkill?

**Comment by samidont0817** [comment]
Hey man. Its been a minute. Just checking into the progress of this. Thanks~

**Comment by qwertyuioplkjhgfd** [comment]
for crafting, still waiting on https://github.com/Slimefun/Slimefun4/pull/3439
you'd have to just use the inventory criteria or multiblock criteria for now (if applicable)
i'll work on the block breaking criteria

**Comment by qwertyuioplkjhgfd** [comment]
added block breaking
(sorry about the delay, was kinda busy)

**Comment by samidont0817** [comment]
You are fine! Thanks man! I appreciate it~

**Comment by AlmostPanda** [comment]
How is crafting criteria going?

**Comment by samidont0817** [comment]
Hey Man! When I was using the plugin, It was going good! I no longer am in need of the plugin due to leaving the team. Thanks for checking up though!

**Comment by AlmostPanda** [comment]
Well our server is based around Skyblock and Slimefun which is pretty good combination, we had a good idea about slimefun missions so I started looking around for some slimefun quest plugin, and I think this is the only one that works the way I want to so Im very gratefull for this plugin/addon.
